/**
 * import 名 → 包名映射表
 *
 * - string: import 名 ≠ 包名时映射（如 cv2 → opencv-python）
 * - null:  Python 内置模块，不需要加载，直接跳过
 * - 未列出: 默认认为 import 名 == 包名（如 numpy → 'numpy'）
 */
export const PACKAGE_NAME_MAP: Record<string, string | null> = {
  // import 名 ≠ 包名
  cv2: 'opencv-python',
  PIL: 'pillow',
  sklearn: 'scikit-learn',
  bs4: 'beautifulsoup4',
  sns: 'seaborn',
  Image: 'pillow',
  numpy: 'numpy',
  np: 'numpy',
  pandas: 'pandas',
  pd: 'pandas',
  matplotlib: 'matplotlib',
  plt: 'matplotlib',
  scipy: 'scipy',
  pillow: 'Pillow',
  requests: 'requests',

  // Python 内置模块（跳过加载）
  math: null,
  sys: null,
  json: null,
  os: null,
  re: null,
  time: null,
  random: null,
  datetime: null,
  collections: null,
  itertools: null,
  functools: null,
  typing: null,
  pathlib: null,
  io: null,
  csv: null,
  hashlib: null,
  copy: null,
  pickle: null,
  base64: null,
  uuid: null,
  enum: null,
  dataclasses: null,
  abc: null,
  string: null,
  statistics: null,
  glob: null,
  shutil: null,
  tempfile: null,
  traceback: null,
  contextlib: null,
  asyncio: null,
  threading: null,
  subprocess: null,
  socket: null,
  urllib: null,
  http: null,
  html: null,
  xml: null,
  sqlite3: null,
  zipfile: null,
  tarfile: null,
  gzip: null,
  zlib: null,
  struct: null,
  ctypes: null,
  decimal: null,
  fractions: null,
  inspect: null,
  pdb: null,
  unittest: null,
  doctest: null,
  importlib: null,
  warnings: null,
  locale: null,
  calendar: null,
  textwrap: null,
  difflib: null,
  codecs: null,
}
